name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r18833"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: ${{ matrix.josm-revision }}
      perform-revision-tagging: ${{ github.repository == 'JOSM/todo' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' && matrix.josm-revision == 'r18833' }}
      java-version: 17

    secrets: inherit

